### ISSUE TITLE
Implement hold event for input that stays high

### ISSUE THREAD

**Issue by martijnversluis** [sourcesimian/mqtt-gpio#1]
I'm using mqtt-gpio to read out touch buttons, and I would be interested to have a hold event that publishes an event every _x_ milliseconds as long as a certain input is high.

It could be configurable like below:

```yaml
pins:
  - gpio: GPIO21
    mode: INPUT
    hold_interval: 200 # Publishes a hold event 200ms after the first "press", and keeps publishing every 200ms until that input becomes low.
```

I would be fun to try to implement it myself, but I'd need some pointers how to get started.
